name: init

on:
  workflow_dispatch:
  schedule:
    # You can change this CRON syntax to customize execute interval
    - cron: "*/5 * * * *"    # - cron: "0 */2 * * *" 2 horas

jobs:
  build:
    runs-on: windows-latest

    env:
      FB_TOK: ${{ secrets.FB_TOK }}
      GIT_TOK: ${{ secrets.GIT_TOK }}
      IMGBB_TOK: ${{ secrets.IMGBB_TOK }}
      GIF_TOK: ${{ secrets.GIF_TOK }}

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.9
        architecture: x64  

    - name: Instalar Dependências
      run: |
        python -m pip install -r requirements.txt

    - name: Executar script Python
      run: python main.py

    - name: auto init
      shell: pwsh
      run: |
        curl -X POST `
        -H "Accept: application/vnd.github.v3+json" `
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" `
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/init.yml/dispatches `
        -d '{"ref":"main"}'
