name: init

on:
  workflow_dispatch:
  schedule:
    # You can change this CRON syntax to customize execute interval
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: windows-latest
    concurrency:
      group: build-${{ github.ref }}

    env:
      fb_tok: ${{ secrets.FB_TOK }}
      git_tok: ${{ secrets.GIT_TOK }}
      imgbb_tok: ${{ secrets.IMGBB_TOK }}
      gif_tok: ${{ secrets.GIF_TOK }}

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python e Cache de Dependências
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.9
        architecture: x64  # Especifique a arquitetura, se necessário

    - name: Cache de Dependências Python
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Executar script Python
      run: python main.py
