name: init

on:
  workflow_dispatch:
  schedule:
    # You can change this CRON syntax to customize execute interval
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: windows-latest
    concurrency:
      group: build-${{ github.ref }}

    env:
      FB_TOK: ${{ secrets.FB_TOK }}
      GIT_TOK: ${{ secrets.GIT_TOK }}
      IMGBB_TOK: ${{ secrets.IMGBB_TOK }}
      GIF_TOK: ${{ secrets.GIF_TOK }}

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.9
        architecture: x64  

    - name: Instalar a fonte COOPBL.TTF
      run: |
        mkdir -p C:\Windows\Fonts
        copy font\COOPBL.TTF C:\Windows\Fonts

    - name: Instalar Dependências
      run: |
        python -m pip install -r requirements.txt

    - name: Executar script Python
      run: python main.py
